version: '3.5'

services:
  
  backend:
    build:
      context: ./ml-kurkkumopo-backend
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    volumes:
      - model:/src/model
  
  frontend:
    build:
      context: ./ml-kurkkumopo-frontend
      dockerfile: Dockerfile
    ports:
      - 3000:3000

  training:
    build:
      context: ./ml-kurkkumopo-training
      dockerfile: Dockerfile
    volumes:
      - model:/src/model
      - images:/src/images

volumes:
  model:
  images:

